version: 2.1

orbs:
  slack: circleci/slack@5.1.1

jobs:
  webhook-notify-on-fail:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - run: 
          name: This is an alert
          environment:
            PAYLOAD: << pipeline.trigger_parameters.webhook.body >>
          command: |
            export WORKFLOW_NAME=$(echo "$PAYLOAD" | jq -r '.workflow.name')
            export WORKFLOW_STATUS=$(echo "$PAYLOAD" | jq -r '.workflow.status')
            export LATEST_REVISION=$(echo "$PAYLOAD" | jq -r '.pipeline.vcs.revision')
            export COMMIT_AUTHOR=$(echo "$PAYLOAD" | jq -r '.pipeline.vcs.commit.author.email')
            export WORKFLOW_URL=$(echo "$PAYLOAD" | jq -r '.workflow.url')

            echo "The payload is:" $PAYLOAD

            if [ "$WORKFLOW_STATUS" = "failed" ]; then
                echo -e "Hi $COMMIT_AUTHOR.\nThe workflow '$WORKFLOW_NAME' completed with the status '$WORKFLOW_STATUS'.\nYou can view this workflow here: '$WORKFLOW_URL'"
                # failing in order to trigger the Slack notification
                # exit 1
            else
                echo "workflow did not fail. No need to send a notification"
            fi
      # - slack/notify:
      #     channel: ABC123
      #     template: basic_fail_1

  pipeline-notify-on-fail:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - run: 
          name: This is an alert
          command: |
            echo "The workflow completed. Go take a look at the latest commit sha: << pipeline.parameters.commit_sha >>"

workflows:
  trigger-notification-webhook: 
    when: 
      equal: [ webhook, << pipeline.trigger_source >> ]
    jobs:
      - webhook-notify-on-fail

  trigger-notification-pipeline: 
    when: 
      equal: [ api, << pipeline.trigger_source >> ]
    jobs:
      - pipeline-notify-on-fail