version: 2.1

jobs:
  notify-on-fail:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run: 
          name: This is an alert
          command: echo "I'm letting you know your Pipeline related to PR123 failed"
      - run: 
          name: This is an alert
          command: |
            PAYLOAD=<< pipeline.trigger_parameters.webhook.body >> | jq -r
            WORKFLOW_NAME=$(echo "$PAYLOAD" | jq -r '.workflow.name')
            echo '"$WORKFLOW_NAME" finished'

workflows:
  build: 
    jobs:
      - notify-on-fail