version: 2.1

jobs:
  notify-on-fail:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run: 
          name: This is an alert
          command: echo "I'm letting you know your Pipeline related to PR123 failed"
      - run: 
          name: This is an alert
          environment:
            WORKFLOW_NAME: << pipeline.trigger_parameters.webhook.body >> | jq .workflow.name
            WORKFLOW_STATUS: << pipeline.trigger_parameters.webhook.body >> | jq .workflow.status
          command: |
            echo "'$WORKFLOW_NAME' completed with the status: '$WORKFLOW_STATUS'"

workflows:
  build: 
    jobs:
      - notify-on-fail