version: 2.1

jobs:
  notify-on-fail:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run: 
          name: This is an alert
          environment:
            PAYLOAD: << pipeline.trigger_parameters.webhook.body >>
          command: |
            export WORKFLOW_NAME=$(echo "$PAYLOAD" | jq -r '.workflow.name')
            export WORKFLOW_STATUS=$(echo "$PAYLOAD" | jq -r '.workflow.status')
            echo "The workflow '$WORKFLOW_NAME' completed with the status '$WORKFLOW_STATUS'"

workflows:
  build: 
    jobs:
      - notify-on-fail