version: 2.1

jobs:
  my-pr-job:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: get pipeline param values
          command: |
            echo pipeline.trigger_parameters.circleci.trigger_type is << pipeline.trigger_parameters.circleci.trigger_type >> 
            echo pipeline.trigger_parameters.circleci.event_time is << pipeline.trigger_parameters.circleci.event_time >>
            echo pipeline.trigger_parameters.circleci.event_type is << pipeline.trigger_parameters.circleci.event_type >>
            echo pipeline.trigger_parameters.github_app.ref is << pipeline.trigger_parameters.github_app.ref >>
            echo pipeline.trigger_parameters.github_app.user_id is << pipeline.trigger_parameters.github_app.user_id >>
            echo pipeline.trigger_parameters.github_app.user_name is << pipeline.trigger_parameters.github_app.user_name >>
            echo pipeline.trigger_parameters.github_app.user_username is << pipeline.trigger_parameters.github_app.user_username >>
            echo pipeline.trigger_parameters.github_app.user_avatar is << pipeline.trigger_parameters.github_app.user_avatar >>
            echo pipeline.trigger_parameters.github_app.repo_name is << pipeline.trigger_parameters.github_app.repo_name >>
            echo pipeline.trigger_parameters.github_app.repo_url is << pipeline.trigger_parameters.github_app.repo_url >>
            echo pipeline.trigger_parameters.github_app.web_url is << pipeline.trigger_parameters.github_app.web_url >>
            echo pipeline.trigger_parameters.github_app.branch is << pipeline.trigger_parameters.github_app.branch >>
      - run: 
          name: Hello from my PR run ci pipeline
          command: echo "Hello from my PR run ci pipeline"

workflows:
  build: 
    jobs:
      - my-pr-job